### ISSUE TITLE
Search bar feature does not work

### ISSUE THREAD

**Issue by hyamero** [krishna8421/public-apis-site#1]
![issuebadge](https://img.shields.io/badge/Issue-Functionality-dddddd?style=for-the-badge&labelColor=000000&logoWidth=15)

The search bar does absolutely nothing as well as the delete button beside it. The search bar also has an outline which is a visual issue.

![issue1](https://user-images.githubusercontent.com/78056869/132321152-72ff8e65-ea40-4ba1-87cc-bac25c6137b8.jpg)

**Comment by d4rkener** [comment]
Can I work on your projects?

**Comment by hyamero** [comment]
My projects or this guy's project?

**Comment by kxnakr** [comment]
Hey @rahulshawdev 

Thanks for your Intrest, I will delete the current main branch soon. See the [Dev](https://github.com/krishna8421/public-apis-site/tree/dev) branch, It will be the new Production branch.

It's not ready yet and I am using Chakra-UI and react-query. If you want you can work on That.

I deployed the Dev branch you can Visit [here](https://public-apis-site-git-dev-krishna8421.vercel.app).

**Comment by kxnakr** [comment]
Done
