### ISSUE TITLE
Category button not working

### ISSUE THREAD

**Issue by hyamero** [krishna8421/public-apis-site#2]
![issuebadge](https://img.shields.io/badge/Issue-Functionality-dddddd?style=for-the-badge&labelColor=000000&logoWidth=15)

The category button on the navbar is _not clickable_, either it's broken or the page simply does not exist.

![issue3](https://user-images.githubusercontent.com/78056869/132321742-3cd640f8-bad8-4ee3-aae9-2b415b4f1412.jpg)

**Comment by d4rkener** [comment]
Can I work on this?

**Comment by d4rkener** [comment]
Where to go from the category button??

**Comment by kxnakr** [comment]
See the Dev Branch,  The main page will contain the category Boxes and a search bar, and when someone searches anything then the category boxes will disappear and the search results will appear. And also a Dynamic page route for opening the category Box which will show all the APIs with that topic and a back button.

I have some exams so I didn't complete it.....

**Comment by kxnakr** [comment]
Done.
