### ISSUE TITLE
Text responsiveness is broken

### ISSUE THREAD

**Issue by hyamero** [krishna8421/public-apis-site#4]
![issuebadge](https://img.shields.io/badge/Issue-Responsiveness-dddddd?style=for-the-badge&labelColor=000000&logoWidth=15)

_Excessive words break API card layout resulting in responsiveness issue._
![issue1](https://user-images.githubusercontent.com/78056869/134922706-c8bab70d-6b74-43a7-b7c5-dd1b37cd9783.jpg)

**Comment by kxnakr** [comment]
Hey @hyamero ,

Thanks for noticing. I'll fix it soon, and do some UI tweak.

**Comment by kxnakr** [comment]
Update: Fixed the responsiveness issue.

Thanks for keeping an eye on the project.
Any suggestions are welcome.

Have a good day✌🏻
